/**
 * PAI Installer v5.0 — Configuration Generator
 * Generates a FALLBACK settings.json from collected user data.
 * Only used when no existing settings.json exists.
 * Produces minimal output — just fields the installer collects.
 * Hooks, permissions, and other config come from the release template.
 */

import type { PAIConfig } from "./types";
import { DEFAULT_VOICES, PAI_VERSION, ALGORITHM_VERSION } from "./types";

/**
 * Generate a minimal fallback settings.json from installer-collected data.
 * This is merged into (not replacing) the release template.
 */
export function generateSettingsJson(config: PAIConfig): Record<string, any> {
  const voiceId = config.voiceId || DEFAULT_VOICES[config.voiceType as keyof typeof DEFAULT_VOICES] || DEFAULT_VOICES.female;

  return {
    env: {
      // PAI_DIR is the active PAI subsystem directory, while PAI_FRAMEWORK_DIR
      // is the selected framework install root.
      // statusline-command.sh, hooks, and tools read PAI_DIR expecting the /PAI
      // suffix; if we write just `~/.claude` here the statusline can't find
      // ALGORITHM/LATEST and falls back to "—". The variable name `config.paiDir`
      // is misleading — it's actually the INSTALL ROOT.
      PAI_DIR: `${config.paiDir}/PAI`,
      PAI_FRAMEWORK: config.framework,
      PAI_FRAMEWORK_DIR: config.paiDir,
      PAI_SETTINGS_PATH: `${config.paiDir}/settings.json`,
      ...(config.projectsDir ? { PROJECTS_DIR: config.projectsDir } : {}),
      PAI_CONFIG_DIR: config.configDir,
      ...(config.dataDir ? { PAI_DATA_DIR: config.dataDir } : {}),
    },

    contextFiles: [],
    _contextFiles_docs:
      "v5.0: contextFiles is empty — constitutional rules live in PAI/PAI_SYSTEM_PROMPT.md, operational procedures in CLAUDE.md/AGENTS.md, and dynamic context is injected by hooks.",

    daidentity: {
      name: config.aiName,
      fullName: `${config.aiName} — Personal AI`,
      displayName: config.aiName.toUpperCase(),
      color: "#3B82F6",
      voices: {
        main: {
          voiceId,
          stability: 0.35,
          similarityBoost: 0.80,
          style: 0.90,
          speed: 1.1,
        },
      },
      startupCatchphrase: config.catchphrase,
    },

    principal: {
      name: config.principalName,
      timezone: config.timezone,
    },

    preferences: {
      temperatureUnit: config.temperatureUnit || "fahrenheit",
    },

    pai: {
      repoUrl: "https://github.com/danielmiessler/PAI",
      version: PAI_VERSION,
      algorithmVersion: ALGORITHM_VERSION,
      framework: config.framework,
    },
  };
}

export function generateCodexConfigToml(config: PAIConfig): string {
  return [
    "# BEGIN PAI MANAGED ROOT CONFIG",
    `# PAI root: ${config.paiDir}/PAI`,
    `# PAI config: ${config.configDir}`,
    "# PAI uses AGENTS.md for Codex instructions.",
    "# PAI hooks are written to hooks.json.",
    "project_doc_fallback_filenames = [\"AGENTS.md\", \"CLAUDE.md\"]",
    "project_doc_max_bytes = 65536",
    "# END PAI MANAGED ROOT CONFIG",
    "",
  ].join("\n");
}

const CODEX_ROOT_BEGIN = "# BEGIN PAI MANAGED ROOT CONFIG";
const CODEX_ROOT_END = "# END PAI MANAGED ROOT CONFIG";

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function firstTomlTableIndex(content: string): number {
  const match = content.match(/^\[.+\]\s*$/m);
  return match?.index ?? content.length;
}

function rootTomlHasKey(content: string, key: string): boolean {
  const root = content.slice(0, firstTomlTableIndex(content));
  return new RegExp(`^\\s*${escapeRegExp(key)}\\s*=`, "m").test(root);
}

function stripManagedCodexRoot(content: string): string {
  return content
    .replace(new RegExp(`\\n?${escapeRegExp(CODEX_ROOT_BEGIN)}[\\s\\S]*?${escapeRegExp(CODEX_ROOT_END)}\\n?`, "g"), "\n")
    .trim();
}

function isLegacyPaiOnlyCodexConfig(content: string): boolean {
  const trimmed = content.trim();
  if (!trimmed.startsWith("# Generated by PAI.") && !trimmed.startsWith("# Generated by the PAI installer.")) return false;
  return !/^\[(?!mcp_servers\.)/m.test(trimmed);
}

function generateCodexRootBlock(config: PAIConfig, existing = ""): string {
  const lines = [
    CODEX_ROOT_BEGIN,
    `# PAI root: ${config.paiDir}/PAI`,
    `# PAI config: ${config.configDir}`,
    "# PAI uses AGENTS.md for Codex instructions.",
    "# PAI hooks are written to hooks.json.",
  ];
  if (!rootTomlHasKey(existing, "project_doc_fallback_filenames")) {
    lines.push("project_doc_fallback_filenames = [\"AGENTS.md\", \"CLAUDE.md\"]");
  }
  if (!rootTomlHasKey(existing, "project_doc_max_bytes")) {
    lines.push("project_doc_max_bytes = 65536");
  }
  lines.push(CODEX_ROOT_END, "");
  return lines.join("\n");
}

export function mergeCodexConfigToml(existing: string, config: PAIConfig): string {
  if (!existing.trim() || isLegacyPaiOnlyCodexConfig(existing)) return generateCodexConfigToml(config);
  const stripped = stripManagedCodexRoot(existing);
  return [
    generateCodexRootBlock(config, stripped).trim(),
    "",
    stripped,
    "",
  ].filter((part) => part.trim().length > 0).join("\n").replace(/\n{3,}/g, "\n\n");
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function powerShellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function hookCommand(config: PAIConfig, hookFile: string): string {
  const adapter = `${config.paiDir}/hooks/FrameworkHookAdapter.ts`;
  const env = [
    ["PAI_DIR", `${config.paiDir}/PAI`],
    ["PAI_DATA_DIR", config.dataDir || ""],
    ["PAI_FRAMEWORK", config.framework],
    ["PAI_FRAMEWORK_DIR", config.paiDir],
    ["PAI_SETTINGS_PATH", `${config.paiDir}/settings.json`],
    ["PAI_CONFIG_DIR", config.configDir],
  ].filter(([, value]) => value);

  return [
    ...env.map(([key, value]) => `${key}=${shellSingleQuote(value)}`),
    "bun",
    shellSingleQuote(adapter),
    "--framework",
    shellSingleQuote(config.framework),
    "--target",
    shellSingleQuote(hookFile),
  ].join(" ");
}

function hookCommandWindows(config: PAIConfig, hookFile: string): string {
  const adapter = `${config.paiDir}\\hooks\\FrameworkHookAdapter.ts`;
  const env = [
    ["PAI_DIR", `${config.paiDir}\\PAI`],
    ["PAI_DATA_DIR", config.dataDir || ""],
    ["PAI_FRAMEWORK", config.framework],
    ["PAI_FRAMEWORK_DIR", config.paiDir],
    ["PAI_SETTINGS_PATH", `${config.paiDir}\\settings.json`],
    ["PAI_CONFIG_DIR", config.configDir],
  ].filter(([, value]) => value);

  const envAssignments = env
    .map(([key, value]) => `$env:${key}=${powerShellSingleQuote(value)};`)
    .join(" ");

  return [
    "powershell",
    "-NoProfile",
    "-ExecutionPolicy",
    "Bypass",
    "-Command",
    powerShellSingleQuote(
      `${envAssignments} bun ${powerShellSingleQuote(adapter)} --framework ${powerShellSingleQuote(config.framework)} --target ${powerShellSingleQuote(hookFile)}`
    ),
  ].join(" ");
}

function commandHook(config: PAIConfig, hookFile: string, timeout = 10): Record<string, any> {
  return {
    type: "command",
    command: hookCommand(config, hookFile),
    commandWindows: hookCommandWindows(config, hookFile),
    timeout,
  };
}

/**
 * Codex supports command hooks. This maps the synchronous command-hook subset
 * of PAI's Claude hooks through FrameworkHookAdapter; HTTP hooks and async
 * command hooks are intentionally omitted because Codex does not execute them.
 */
export function generateCodexHooksJson(config: PAIConfig): Record<string, any> {
  return {
    hooks: {
      SessionStart: [
        {
          matcher: "startup|resume",
          hooks: [
            commandHook(config, "KittyEnvPersist.hook.ts"),
            commandHook(config, "LoadContext.hook.ts", 20),
          ],
        },
      ],
      PreToolUse: [
        {
          matcher: "Bash|Shell|Write|Edit|MultiEdit|Read|apply_patch",
          hooks: [
            commandHook(config, "SecurityPipeline.hook.ts"),
          ],
        },
      ],
      PostToolUse: [
        {
          matcher: "WebFetch|WebSearch",
          hooks: [
            commandHook(config, "ContentScanner.hook.ts", 5),
          ],
        },
        {
          matcher: "Write|Edit|MultiEdit|apply_patch",
          hooks: [
            commandHook(config, "TelosSummarySync.hook.ts", 5),
          ],
        },
        {
          hooks: [
            commandHook(config, "ToolActivityTracker.hook.ts", 5),
          ],
        },
      ],
      UserPromptSubmit: [
        {
          hooks: [
            commandHook(config, "PromptGuard.hook.ts", 5),
            commandHook(config, "RepeatDetection.hook.ts", 5),
          ],
        },
      ],
      PreCompact: [
        {
          matcher: "*",
          hooks: [
            commandHook(config, "PreCompact.hook.ts", 10),
          ],
        },
      ],
      Stop: [
        {
          hooks: [
            commandHook(config, "LastResponseCache.hook.ts", 10),
            commandHook(config, "ResponseTabReset.hook.ts", 10),
            commandHook(config, "VoiceCompletion.hook.ts", 10),
            commandHook(config, "DocIntegrity.hook.ts", 20),
          ],
        },
      ],
    },
  };
}

export function generateOpenCodeConfigJson(config: PAIConfig): Record<string, any> {
  return {
    "$schema": "https://opencode.ai/config.json",
    instructions: ["AGENTS.md"],
    env: {
      PAI_DIR: `${config.paiDir}/PAI`,
      PAI_FRAMEWORK: config.framework,
      PAI_FRAMEWORK_DIR: config.paiDir,
      PAI_SETTINGS_PATH: `${config.paiDir}/settings.json`,
      PAI_CONFIG_DIR: config.configDir,
      ...(config.dataDir ? { PAI_DATA_DIR: config.dataDir } : {}),
      ...(config.projectsDir ? { PROJECTS_DIR: config.projectsDir } : {}),
    },
    pai: {
      repoUrl: "https://github.com/danielmiessler/PAI",
      version: PAI_VERSION,
      algorithmVersion: ALGORITHM_VERSION,
      framework: config.framework,
    },
  };
}
