/**
 * PAI Installer v5.0 — Configuration Generator
 * Generates a FALLBACK settings.json from collected user data.
 * Only used when no existing settings.json exists.
 * Produces minimal output — just fields the installer collects.
 * Hooks, permissions, and other config come from the release template.
 */

import type { PAIConfig } from "./types";
import { DEFAULT_VOICES, PAI_VERSION, ALGORITHM_VERSION } from "./types";
import { existsSync } from "fs";
import { join } from "path";

/**
 * Generate a minimal fallback settings.json from installer-collected data.
 * This is merged into (not replacing) the release template.
 */
export function generateSettingsJson(config: PAIConfig): Record<string, any> {
  const voiceId = config.voiceId || DEFAULT_VOICES[config.voiceType as keyof typeof DEFAULT_VOICES] || DEFAULT_VOICES.female;

  return {
    env: {
      // PAI_DIR is the active PAI subsystem directory, while PAI_FRAMEWORK_DIR
      // is the selected framework install root.
      // statusline-command.sh, hooks, and tools read PAI_DIR expecting the /PAI
      // suffix; if we write just `~/.claude` here the statusline can't find
      // ALGORITHM/LATEST and falls back to "—". The variable name `config.paiDir`
      // is misleading — it's actually the INSTALL ROOT.
      PAI_DIR: `${config.paiDir}/PAI`,
      PAI_FRAMEWORK: config.framework,
      PAI_FRAMEWORK_DIR: config.paiDir,
      PAI_SETTINGS_PATH: `${config.paiDir}/settings.json`,
      ...(config.projectsDir ? { PROJECTS_DIR: config.projectsDir } : {}),
      PAI_CONFIG_DIR: config.configDir,
      ...(config.dataDir ? { PAI_DATA_DIR: config.dataDir } : {}),
    },

    contextFiles: [],
    _contextFiles_docs:
      "v5.0: contextFiles is empty — constitutional rules live in PAI/PAI_SYSTEM_PROMPT.md, operational procedures in CLAUDE.md/AGENTS.md, and dynamic context is injected by hooks.",

    daidentity: {
      name: config.aiName,
      fullName: `${config.aiName} — Personal AI`,
      displayName: config.aiName.toUpperCase(),
      color: "#3B82F6",
      voices: {
        main: {
          voiceId,
          stability: 0.35,
          similarityBoost: 0.80,
          style: 0.90,
          speed: 1.1,
        },
      },
      startupCatchphrase: config.catchphrase,
    },

    principal: {
      name: config.principalName,
      timezone: config.timezone,
    },

    preferences: {
      temperatureUnit: config.temperatureUnit || "fahrenheit",
    },

    pai: {
      repoUrl: "https://github.com/danielmiessler/PAI",
      version: PAI_VERSION,
      algorithmVersion: ALGORITHM_VERSION,
      framework: config.framework,
    },
  };
}

export function generateCodexConfigToml(config: PAIConfig): string {
  return [
    "# BEGIN PAI MANAGED ROOT CONFIG",
    `# PAI root: ${config.paiDir}/PAI`,
    `# PAI config: ${config.configDir}`,
    "# PAI uses AGENTS.md plus RTK.md for Codex instructions.",
    "# PAI hooks are written to hooks.json.",
    "project_doc_fallback_filenames = [\"AGENTS.md\", \"RTK.md\", \"CLAUDE.md\"]",
    "project_doc_max_bytes = 65536",
    "# END PAI MANAGED ROOT CONFIG",
    "",
  ].join("\n");
}

const CODEX_ROOT_BEGIN = "# BEGIN PAI MANAGED ROOT CONFIG";
const CODEX_ROOT_END = "# END PAI MANAGED ROOT CONFIG";

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function firstTomlTableIndex(content: string): number {
  const match = content.match(/^\[.+\]\s*$/m);
  return match?.index ?? content.length;
}

function rootTomlHasKey(content: string, key: string): boolean {
  const root = content.slice(0, firstTomlTableIndex(content));
  return new RegExp(`^\\s*${escapeRegExp(key)}\\s*=`, "m").test(root);
}

function stripManagedCodexRoot(content: string): string {
  return content
    .replace(new RegExp(`\\n?${escapeRegExp(CODEX_ROOT_BEGIN)}[\\s\\S]*?${escapeRegExp(CODEX_ROOT_END)}\\n?`, "g"), "\n")
    .trim();
}

function isLegacyPaiOnlyCodexConfig(content: string): boolean {
  const trimmed = content.trim();
  if (!trimmed.startsWith("# Generated by PAI.") && !trimmed.startsWith("# Generated by the PAI installer.")) return false;
  return !/^\[(?!mcp_servers\.)/m.test(trimmed);
}

function generateCodexRootBlock(config: PAIConfig, existing = ""): string {
  const lines = [
    CODEX_ROOT_BEGIN,
    `# PAI root: ${config.paiDir}/PAI`,
    `# PAI config: ${config.configDir}`,
    "# PAI uses AGENTS.md plus RTK.md for Codex instructions.",
    "# PAI hooks are written to hooks.json.",
  ];
  if (!rootTomlHasKey(existing, "project_doc_fallback_filenames")) {
    lines.push("project_doc_fallback_filenames = [\"AGENTS.md\", \"RTK.md\", \"CLAUDE.md\"]");
  }
  if (!rootTomlHasKey(existing, "project_doc_max_bytes")) {
    lines.push("project_doc_max_bytes = 65536");
  }
  lines.push(CODEX_ROOT_END, "");
  return lines.join("\n");
}

export function mergeCodexConfigToml(existing: string, config: PAIConfig): string {
  if (!existing.trim() || isLegacyPaiOnlyCodexConfig(existing)) return generateCodexConfigToml(config);
  const stripped = stripManagedCodexRoot(existing);
  return [
    generateCodexRootBlock(config, stripped).trim(),
    "",
    stripped,
    "",
  ].filter((part) => part.trim().length > 0).join("\n").replace(/\n{3,}/g, "\n\n");
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function outerHookTimeout(timeout: number): number {
  return timeout + 5;
}

function hookTargetArg(hookFile: string | string[]): string {
  return Array.isArray(hookFile) ? hookFile.join(",") : hookFile;
}

function hookCommandPosix(config: PAIConfig, hookFile: string | string[], timeout = 10): string {
  const adapter = `${config.paiDir}/hooks/FrameworkHookAdapter.ts`;
  const env = [
    ["PAI_DIR", `${config.paiDir}/PAI`],
    ["PAI_DATA_DIR", config.dataDir || ""],
    ["PAI_FRAMEWORK", config.framework],
    ["PAI_FRAMEWORK_DIR", config.paiDir],
    ["PAI_SETTINGS_PATH", `${config.paiDir}/settings.json`],
    ["PAI_CONFIG_DIR", config.configDir],
  ].filter(([, value]) => value);

  return [
    ...env.map(([key, value]) => `${key}=${shellSingleQuote(value)}`),
    "bun",
    shellSingleQuote(adapter),
    "--framework",
    shellSingleQuote(config.framework),
    "--target",
    shellSingleQuote(hookTargetArg(hookFile)),
    "--timeout-ms",
    shellSingleQuote(String(timeout * 1000)),
  ].join(" ");
}

function windowsCommandArg(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}

function existingPath(value: string | undefined): string {
  return value && existsSync(value) ? value : "";
}

function windowsBunExe(): string {
  const home = process.env.HOME || process.env.USERPROFILE || "";
  const candidates = [
    existingPath(process.env.PAI_BUN_EXE),
    existingPath(process.env.BUN_INSTALL ? join(process.env.BUN_INSTALL, "bin", "bun.exe") : ""),
    existingPath(home ? join(home, ".bun", "bin", "bun.exe") : ""),
    existingPath(process.env.APPDATA ? join(process.env.APPDATA, "npm", "node_modules", "bun", "bin", "bun.exe") : ""),
    existingPath(process.env.LOCALAPPDATA ? join(process.env.LOCALAPPDATA, "bun", "bin", "bun.exe") : ""),
  ].filter(Boolean);
  return candidates[0] || "bun.exe";
}

function hookCommandWindowsDirect(config: PAIConfig, hookFile: string | string[], timeout = 10): string {
  const adapter = `${config.paiDir}\\hooks\\FrameworkHookAdapter.ts`;
  const target = hookTargetArg(hookFile);
  const timeoutMs = String(timeout * 1000);
  return [
    windowsCommandArg(windowsBunExe()),
    windowsCommandArg(adapter),
    "--framework",
    windowsCommandArg(config.framework),
    "--target",
    windowsCommandArg(target),
    "--timeout-ms",
    windowsCommandArg(timeoutMs),
  ].join(" ");
}

function hookCommand(config: PAIConfig, hookFile: string | string[], timeout = 10): string {
  return process.platform === "win32"
    ? hookCommandWindowsDirect(config, hookFile, timeout)
    : hookCommandPosix(config, hookFile, timeout);
}

function hookCommandWindows(config: PAIConfig, hookFile: string | string[], timeout = 10): string {
  return hookCommandWindowsDirect(config, hookFile, timeout);
}

function commandHook(config: PAIConfig, hookFile: string | string[], timeout = 10): Record<string, any> {
  return {
    type: "command",
    command: hookCommand(config, hookFile, timeout),
    commandWindows: hookCommandWindows(config, hookFile, timeout),
    timeout: outerHookTimeout(timeout),
  };
}

/**
 * Codex supports command hooks. This emits Codex-native hook groups first:
 * Codex tool/event matchers, Codex block decisions, Codex command updates, and
 * Windows-safe command runners are the contract tested by
 * CodexHookContractSmokeTest. FrameworkHookAdapter is only the compatibility
 * bridge that lets shared PAI hook implementations receive normalized input.
 *
 * HTTP hooks remain Pulse-owned for Claude. Codex gets command equivalents
 * where they exist; Pulse-only routes such as skill-guard/agent-guard are not
 * emitted here because Codex does not execute HTTP hook entries.
 */
export function generateCodexHooksJson(config: PAIConfig): Record<string, any> {
  return {
    hooks: {
      SessionStart: [
        {
          matcher: "startup|resume",
          hooks: [
            commandHook(config, "KittyEnvPersist.hook.ts"),
            commandHook(config, "LoadContext.hook.ts", 20),
            commandHook(config, "StartupSelfCheck.hook.ts", 5),
            commandHook(config, "KVSync.hook.ts", 5),
          ],
        },
      ],
      PreToolUse: [
        {
          matcher: "Bash|Shell",
          hooks: [
            commandHook(config, ["SecurityPipeline.hook.ts", "RtkPreToolUse.hook.js"]),
          ],
        },
        {
          matcher: "Write|Edit|MultiEdit|Read|apply_patch",
          hooks: [
            commandHook(config, "SecurityPipeline.hook.ts"),
          ],
        },
        {
          matcher: "AskUserQuestion|request_user_input",
          hooks: [
            commandHook(config, "SetQuestionTab.hook.ts", 5),
          ],
        },
        {
          matcher: "Agent",
          hooks: [
            commandHook(config, "AgentInvocation.hook.ts", 5),
          ],
        },
      ],
      PostToolUse: [
        {
          matcher: "WebFetch|WebSearch",
          hooks: [
            commandHook(config, "ContentScanner.hook.ts", 5),
          ],
        },
        {
          matcher: "AskUserQuestion|request_user_input",
          hooks: [
            commandHook(config, "QuestionAnswered.hook.ts", 5),
          ],
        },
        {
          matcher: "Write|Edit|MultiEdit|apply_patch",
          hooks: [
            commandHook(config, ["TelosSummarySync.hook.ts", "ISASync.hook.ts", "CheckpointPerISC.hook.ts"], 10),
          ],
        },
        {
          matcher: "Agent",
          hooks: [
            commandHook(config, "AgentInvocation.hook.ts", 5),
          ],
        },
        {
          matcher: "*",
          hooks: [
            commandHook(config, "ToolActivityTracker.hook.ts", 5),
          ],
        },
        {
          // Catch-all injection scan: Claude runs ContentScanner over every
          // tool result (not just WebFetch/WebSearch) so external content
          // surfaced by any tool is checked for prompt injection. Mirror that
          // here so Codex gets the same defense-in-depth coverage. PostToolUse
          // cannot block; the hook only injects a warning into context.
          matcher: "*",
          hooks: [
            commandHook(config, "ContentScanner.hook.ts", 5),
          ],
        },
      ],
      UserPromptSubmit: [
        {
          hooks: [
            commandHook(config, ["PromptGuard.hook.ts", "RepeatDetection.hook.ts", "PromptProcessing.hook.ts"], 35),
            commandHook(config, "SatisfactionCapture.hook.ts", 5),
          ],
        },
      ],
      PreCompact: [
        {
          matcher: "*",
          hooks: [
            commandHook(config, "PreCompact.hook.ts", 10),
          ],
        },
      ],
      Stop: [
        {
          hooks: [
            commandHook(config, "LastResponseCache.hook.ts", 10),
            commandHook(config, "ResponseTabReset.hook.ts", 10),
            commandHook(config, "VoiceCompletion.hook.ts", 10),
            commandHook(config, "DocIntegrity.hook.ts", 20),
          ],
        },
      ],
      SessionEnd: [
        {
          hooks: [
            commandHook(config, "SessionEndDispatcher.hook.ts", 5),
          ],
        },
      ],
    },
  };
}

export function generateOpenCodeConfigJson(config: PAIConfig): Record<string, any> {
  void config;
  return {
    "$schema": "https://opencode.ai/config.json",
    instructions: ["AGENTS.md"],
  };
}

function stripUnsupportedOpenCodeKeys(config: Record<string, any>): Record<string, any> {
  const clean: Record<string, any> = {};
  if (!config || typeof config !== "object") return clean;
  for (const [key, value] of Object.entries(config)) {
    if (key === "env" || key === "pai") continue;
    clean[key] = value;
  }
  return clean;
}

export function mergeOpenCodeConfigJson(existing: Record<string, any>, generated: Record<string, any>): Record<string, any> {
  const cleanExisting = stripUnsupportedOpenCodeKeys(existing);
  const cleanGenerated = stripUnsupportedOpenCodeKeys(generated);
  return {
    ...cleanExisting,
    ...cleanGenerated,
    instructions: cleanGenerated.instructions || cleanExisting.instructions || ["AGENTS.md"],
    ...(cleanExisting.mcp || cleanGenerated.mcp ? {
      mcp: {
        ...(cleanExisting.mcp && typeof cleanExisting.mcp === "object" ? cleanExisting.mcp : {}),
        ...(cleanGenerated.mcp && typeof cleanGenerated.mcp === "object" ? cleanGenerated.mcp : {}),
      },
    } : {}),
  };
}
